# Generated by Django 5.2.8 on 2025-11-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(default='User@gmail.com', max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('profile', models.URLField(default='empty')),
            ],
        ),
    ]
